EXERCISES = [
    # === CHEST ===
    {'name': 'Bench Press (Barbell)', 'muscle_group': 'chest', 'equipment': 'barbell'},
    {'name': 'Bench Press (Dumbbell)', 'muscle_group': 'chest', 'equipment': 'dumbbell'},
    {'name': 'Incline Bench Press (Barbell)', 'muscle_group': 'chest', 'equipment': 'barbell'},
    {'name': 'Incline Bench Press (Dumbbell)', 'muscle_group': 'chest', 'equipment': 'dumbbell'},
    {'name': 'Decline Bench Press (Barbell)', 'muscle_group': 'chest', 'equipment': 'barbell'},
    {'name': 'Chest Fly (Dumbbell)', 'muscle_group': 'chest', 'equipment': 'dumbbell'},
    {'name': 'Chest Fly (Cable)', 'muscle_group': 'chest', 'equipment': 'cable'},
    {'name': 'Cable Crossover', 'muscle_group': 'chest', 'equipment': 'cable'},
    {'name': 'Push-Up', 'muscle_group': 'chest', 'equipment': 'bodyweight'},
    {'name': 'Dips (Chest)', 'muscle_group': 'chest', 'equipment': 'bodyweight'},
    {'name': 'Chest Press (Machine)', 'muscle_group': 'chest', 'equipment': 'machine'},
    {'name': 'Pec Deck', 'muscle_group': 'chest', 'equipment': 'machine'},

    # === BACK ===
    {'name': 'Deadlift (Barbell)', 'muscle_group': 'back', 'equipment': 'barbell'},
    {'name': 'Bent-Over Row (Barbell)', 'muscle_group': 'back', 'equipment': 'barbell'},
    {'name': 'Bent-Over Row (Dumbbell)', 'muscle_group': 'back', 'equipment': 'dumbbell'},
    {'name': 'Pull-Up', 'muscle_group': 'back', 'equipment': 'bodyweight'},
    {'name': 'Chin-Up', 'muscle_group': 'back', 'equipment': 'bodyweight'},
    {'name': 'Lat Pulldown', 'muscle_group': 'back', 'equipment': 'cable'},
    {'name': 'Seated Cable Row', 'muscle_group': 'back', 'equipment': 'cable'},
    {'name': 'T-Bar Row', 'muscle_group': 'back', 'equipment': 'barbell'},
    {'name': 'Face Pull', 'muscle_group': 'back', 'equipment': 'cable'},
    {'name': 'Single-Arm Dumbbell Row', 'muscle_group': 'back', 'equipment': 'dumbbell'},
    {'name': 'Hyperextension', 'muscle_group': 'back', 'equipment': 'bodyweight'},
    {'name': 'Good Morning', 'muscle_group': 'back', 'equipment': 'barbell'},
    {'name': 'Rack Pull', 'muscle_group': 'back', 'equipment': 'barbell'},

    # === SHOULDERS ===
    {'name': 'Overhead Press (Barbell)', 'muscle_group': 'shoulders', 'equipment': 'barbell'},
    {'name': 'Overhead Press (Dumbbell)', 'muscle_group': 'shoulders', 'equipment': 'dumbbell'},
    {'name': 'Arnold Press', 'muscle_group': 'shoulders', 'equipment': 'dumbbell'},
    {'name': 'Lateral Raise (Dumbbell)', 'muscle_group': 'shoulders', 'equipment': 'dumbbell'},
    {'name': 'Lateral Raise (Cable)', 'muscle_group': 'shoulders', 'equipment': 'cable'},
    {'name': 'Front Raise (Dumbbell)', 'muscle_group': 'shoulders', 'equipment': 'dumbbell'},
    {'name': 'Reverse Fly (Dumbbell)', 'muscle_group': 'shoulders', 'equipment': 'dumbbell'},
    {'name': 'Reverse Fly (Cable)', 'muscle_group': 'shoulders', 'equipment': 'cable'},
    {'name': 'Upright Row', 'muscle_group': 'shoulders', 'equipment': 'barbell'},
    {'name': 'Shrugs (Barbell)', 'muscle_group': 'shoulders', 'equipment': 'barbell'},
    {'name': 'Shrugs (Dumbbell)', 'muscle_group': 'shoulders', 'equipment': 'dumbbell'},
    {'name': 'Shoulder Press (Machine)', 'muscle_group': 'shoulders', 'equipment': 'machine'},

    # === ARMS ===
    {'name': 'Bicep Curl (Barbell)', 'muscle_group': 'arms', 'equipment': 'barbell'},
    {'name': 'Bicep Curl (Dumbbell)', 'muscle_group': 'arms', 'equipment': 'dumbbell'},
    {'name': 'Hammer Curl', 'muscle_group': 'arms', 'equipment': 'dumbbell'},
    {'name': 'Preacher Curl', 'muscle_group': 'arms', 'equipment': 'barbell'},
    {'name': 'Concentration Curl', 'muscle_group': 'arms', 'equipment': 'dumbbell'},
    {'name': 'Cable Curl', 'muscle_group': 'arms', 'equipment': 'cable'},
    {'name': 'Incline Dumbbell Curl', 'muscle_group': 'arms', 'equipment': 'dumbbell'},
    {'name': 'Tricep Pushdown (Cable)', 'muscle_group': 'arms', 'equipment': 'cable'},
    {'name': 'Tricep Overhead Extension (Dumbbell)', 'muscle_group': 'arms', 'equipment': 'dumbbell'},
    {'name': 'Tricep Overhead Extension (Cable)', 'muscle_group': 'arms', 'equipment': 'cable'},
    {'name': 'Skull Crusher', 'muscle_group': 'arms', 'equipment': 'barbell'},
    {'name': 'Close-Grip Bench Press', 'muscle_group': 'arms', 'equipment': 'barbell'},
    {'name': 'Dips (Tricep)', 'muscle_group': 'arms', 'equipment': 'bodyweight'},
    {'name': 'Diamond Push-Up', 'muscle_group': 'arms', 'equipment': 'bodyweight'},
    {'name': 'Wrist Curl', 'muscle_group': 'arms', 'equipment': 'dumbbell'},

    # === LEGS ===
    {'name': 'Squat (Barbell)', 'muscle_group': 'legs', 'equipment': 'barbell'},
    {'name': 'Front Squat', 'muscle_group': 'legs', 'equipment': 'barbell'},
    {'name': 'Goblet Squat', 'muscle_group': 'legs', 'equipment': 'dumbbell'},
    {'name': 'Leg Press', 'muscle_group': 'legs', 'equipment': 'machine'},
    {'name': 'Hack Squat', 'muscle_group': 'legs', 'equipment': 'machine'},
    {'name': 'Lunge (Barbell)', 'muscle_group': 'legs', 'equipment': 'barbell'},
    {'name': 'Lunge (Dumbbell)', 'muscle_group': 'legs', 'equipment': 'dumbbell'},
    {'name': 'Bulgarian Split Squat', 'muscle_group': 'legs', 'equipment': 'dumbbell'},
    {'name': 'Romanian Deadlift (Barbell)', 'muscle_group': 'legs', 'equipment': 'barbell'},
    {'name': 'Romanian Deadlift (Dumbbell)', 'muscle_group': 'legs', 'equipment': 'dumbbell'},
    {'name': 'Leg Extension', 'muscle_group': 'legs', 'equipment': 'machine'},
    {'name': 'Leg Curl (Lying)', 'muscle_group': 'legs', 'equipment': 'machine'},
    {'name': 'Leg Curl (Seated)', 'muscle_group': 'legs', 'equipment': 'machine'},
    {'name': 'Calf Raise (Standing)', 'muscle_group': 'legs', 'equipment': 'machine'},
    {'name': 'Calf Raise (Seated)', 'muscle_group': 'legs', 'equipment': 'machine'},
    {'name': 'Hip Thrust (Barbell)', 'muscle_group': 'legs', 'equipment': 'barbell'},
    {'name': 'Step-Up', 'muscle_group': 'legs', 'equipment': 'dumbbell'},
    {'name': 'Pistol Squat', 'muscle_group': 'legs', 'equipment': 'bodyweight'},
    {'name': 'Hip Adductor (Machine)', 'muscle_group': 'legs', 'equipment': 'machine'},
    {'name': 'Hip Abductor (Machine)', 'muscle_group': 'legs', 'equipment': 'machine'},

    # === CORE ===
    {'name': 'Plank', 'muscle_group': 'core', 'equipment': 'bodyweight'},
    {'name': 'Crunch', 'muscle_group': 'core', 'equipment': 'bodyweight'},
    {'name': 'Sit-Up', 'muscle_group': 'core', 'equipment': 'bodyweight'},
    {'name': 'Hanging Leg Raise', 'muscle_group': 'core', 'equipment': 'bodyweight'},
    {'name': 'Hanging Knee Raise', 'muscle_group': 'core', 'equipment': 'bodyweight'},
    {'name': 'Cable Crunch', 'muscle_group': 'core', 'equipment': 'cable'},
    {'name': 'Ab Wheel Rollout', 'muscle_group': 'core', 'equipment': 'other'},
    {'name': 'Russian Twist', 'muscle_group': 'core', 'equipment': 'bodyweight'},
    {'name': 'Mountain Climber', 'muscle_group': 'core', 'equipment': 'bodyweight'},
    {'name': 'Dead Bug', 'muscle_group': 'core', 'equipment': 'bodyweight'},
    {'name': 'Side Plank', 'muscle_group': 'core', 'equipment': 'bodyweight'},
    {'name': 'Woodchop (Cable)', 'muscle_group': 'core', 'equipment': 'cable'},

    # === CARDIO ===
    {'name': 'Treadmill Running', 'muscle_group': 'cardio', 'equipment': 'machine'},
    {'name': 'Cycling (Stationary)', 'muscle_group': 'cardio', 'equipment': 'machine'},
    {'name': 'Rowing Machine', 'muscle_group': 'cardio', 'equipment': 'machine'},
    {'name': 'Elliptical', 'muscle_group': 'cardio', 'equipment': 'machine'},
    {'name': 'Stair Climber', 'muscle_group': 'cardio', 'equipment': 'machine'},
    {'name': 'Jump Rope', 'muscle_group': 'cardio', 'equipment': 'other'},
    {'name': 'Burpee', 'muscle_group': 'cardio', 'equipment': 'bodyweight'},
    {'name': 'Kettlebell Swing', 'muscle_group': 'cardio', 'equipment': 'kettlebell'},
    {'name': 'Battle Ropes', 'muscle_group': 'cardio', 'equipment': 'other'},
    {'name': 'Box Jump', 'muscle_group': 'cardio', 'equipment': 'other'},
]
